GET http://localhost:3001/api/notes HTTP/1.1

###

GET http://localhost:3001/api/notes/ HTTP/1.1

###

POST http://localhost:3001/api/notes?userId= HTTP/1.1
content-type: application/json

{
    "content": "sample",
    "important": true
}

###
GET http://localhost:3001/api/notes/63cd806b7a1f20f13abc8efd